// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://apdradsukadmakdybffj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFwZHJhZHN1a2FkbWFrZHliZmZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1NTY4MTgsImV4cCI6MjA3MTEzMjgxOH0.5mZcAT_Ep2B8ezsNIdiaJrDbnNUR_4EuUUeRJhDF3K8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});